DEFAULT_MAPPING = [
    {
        "Source Field": "IfcProduct.GlobalId",
        "Digital Twin Property": "source_global_id",
        "Target Group": "Core",
    },
    {
        "Source Field": "IfcProduct.Name",
        "Digital Twin Property": "asset_name",
        "Target Group": "Core",
    },
    {
        "Source Field": "IFC entity type",
        "Digital Twin Property": "ifc_class",
        "Target Group": "Core",
    },
    {
        "Source Field": "IfcBuilding.Name",
        "Digital Twin Property": "building",
        "Target Group": "Location",
    },
    {
        "Source Field": "IfcBuildingStorey.Name",
        "Digital Twin Property": "floor",
        "Target Group": "Location",
    },
    {
        "Source Field": "IfcSpace.Name",
        "Digital Twin Property": "room_zone",
        "Target Group": "Location",
    },
    {
        "Source Field": "Pset_*Common",
        "Digital Twin Property": "technical_properties",
        "Target Group": "Property",
    },
    {
        "Source Field": "BaseQuantities",
        "Digital Twin Property": "quantity_properties",
        "Target Group": "Property",
    },
    {
        "Source Field": "ArchiCADProperties",
        "Digital Twin Property": "raw_metadata",
        "Target Group": "Traceability",
    },
]

ASSET_SCHEMA = {
    "asset_id": "",
    "dt_asset_code": "",
    "asset_name": "",
    "asset_type": "",
    "ifc_class": "",
    "system": "",
    "system_code": "",
    "discipline": "",
    "location": "",
    "floor": "",
    "room_zone": "",
    "manufacturer": "",
    "model": "",
    "serial_number": "",
    "installation_date": "",
    "warranty_start_date": "",
    "warranty_end_date": "",
    "warranty": "",
    "maintenance_info": "",
    "criticality": "",
    "maintainable": "",
    "expected_life_years": "",
    "maintenance_strategy": "",
    "cmms_asset_id": "",
    "spare_part_group": "",
    "manual_url": "",
    "device_id": "",
    "gateway_id": "",
    "protocol": "",
    "bms_device_id": "",
    "modbus_slave_id": "",
    "mqtt_topic": "",
    "rest_endpoint": "",
    "onvif_profile_url": "",
    "polling_interval_sec": "",
    "realtime_enabled": "",
    "history_enabled": "",
    "point_template": "",
    "review_status": "",
    "mapping_status": "",
    "status": "",
    "source_global_id": "",
    "ifc_guid": "",
    "source_file": "",
    "technical_properties": {},
    "quantity_properties": {},
    "source_reference": {},
    "raw_metadata": {},
}

TECHNICAL_PROPERTY_NAMES = {
    "ThermalTransmittance",
    "LoadBearing",
    "IsExternal",
    "FireRating",
    "AcousticRating",
}

QUANTITY_PROPERTY_NAMES = {"Area", "Volume", "Length", "Count"}

NOISE_KEYWORDS = {
    "2d display",
    "symbol pen",
    "fill",
    "hatch",
    "label",
    "marker",
    "ui setting",
    "archicad",
}
