REQUIRED_FIELDS = [
    "asset_id",
    "asset_name",
    "asset_type",
    "ifc_class",
    "system",
    "location",
    "floor",
    "room_zone",
    "manufacturer",
    "model",
    "serial_number",
    "warranty",
    "maintenance_info",
    "status",
]

FIELD_LABELS = {
    "asset_id": "Asset ID",
    "asset_name": "Asset Name",
    "asset_type": "Asset Type",
    "ifc_class": "IFC Class",
    "system": "System",
    "system_code": "System Code",
    "location": "Location",
    "floor": "Floor",
    "room_zone": "Room/Zone",
    "manufacturer": "Manufacturer",
    "model": "Model",
    "serial_number": "Serial Number",
    "warranty": "Warranty",
    "maintenance_info": "Maintenance Info",
    "criticality": "Criticality",
    "maintainable": "Maintainable",
    "maintenance_strategy": "Maintenance Strategy",
    "cmms_asset_id": "CMMS Asset ID",
    "installation_date": "Installation Date",
    "warranty_start_date": "Warranty Start Date",
    "warranty_end_date": "Warranty End Date",
    "expected_life_years": "Expected Life Years",
    "spare_part_group": "Spare Part Group",
    "manual_url": "Manual URL",
    "device_id": "Device ID",
    "gateway_id": "Gateway ID",
    "protocol": "Protocol",
    "bms_device_id": "BMS Device ID",
    "modbus_slave_id": "Modbus Slave ID",
    "mqtt_topic": "MQTT Topic",
    "rest_endpoint": "REST Endpoint",
    "onvif_profile_url": "ONVIF Profile URL",
    "polling_interval_sec": "Polling Interval Sec",
    "realtime_enabled": "Realtime Enabled",
    "history_enabled": "History Enabled",
    "point_template": "Point Template",
    "source_global_id": "IFC GlobalId",
    "status": "Status",
}

SEVERITY_BY_FIELD = {
    "asset_id": "High",
    "asset_name": "High",
    "asset_type": "High",
    "ifc_class": "High",
    "system": "Medium",
    "system_code": "High",
    "location": "Medium",
    "floor": "Medium",
    "room_zone": "Medium",
    "manufacturer": "Low",
    "model": "Low",
    "serial_number": "Low",
    "warranty": "Low",
    "maintenance_info": "Low",
    "criticality": "Medium",
    "maintainable": "Medium",
    "maintenance_strategy": "Medium",
    "cmms_asset_id": "Medium",
    "device_id": "Medium",
    "gateway_id": "Medium",
    "protocol": "Medium",
    "polling_interval_sec": "Low",
    "realtime_enabled": "Medium",
    "history_enabled": "Low",
    "point_template": "Low",
    "source_global_id": "High",
    "status": "Medium",
}
