REQUIRED_FIELDS = [
    "asset_id",
    "asset_name",
    "asset_type",
    "ifc_class",
    "system",
    "location",
    "floor",
    "room_zone",
    "manufacturer",
    "model",
    "serial_number",
    "warranty",
    "maintenance_info",
    "status",
]

FIELD_LABELS = {
    "asset_id": "Asset ID",
    "asset_name": "Asset Name",
    "asset_type": "Asset Type",
    "ifc_class": "IFC Class",
    "system": "System",
    "location": "Location",
    "floor": "Floor",
    "room_zone": "Room/Zone",
    "manufacturer": "Manufacturer",
    "model": "Model",
    "serial_number": "Serial Number",
    "warranty": "Warranty",
    "maintenance_info": "Maintenance Info",
    "status": "Status",
}

SEVERITY_BY_FIELD = {
    "asset_id": "High",
    "asset_name": "High",
    "asset_type": "High",
    "ifc_class": "High",
    "system": "Medium",
    "location": "Medium",
    "floor": "Medium",
    "room_zone": "Medium",
    "manufacturer": "Low",
    "model": "Low",
    "serial_number": "Low",
    "warranty": "Low",
    "maintenance_info": "Low",
    "status": "Medium",
}
